#Change this file name to application.yml
GITHUB_CLIENT_ID: ""
GITHUB_CLIENT_SECRET: ""
#match with your github page
GITHUB_CALL_BACK_URL: "http://yourdomain:yourport/users/github_callback"
SMTP_SERVER: ""
SMTP_PORT: ""
YOUR_DOMAIN: ""
SMTP_USER_NAME: ""
SMTP_USER_PASS: ""
