development:
  host: art.cs.drexel.edu
  adapter: postgresql
  encoding: unicode
  database: kevin_test
  username: kevin_test
  password: qtdtestme

test:
  host: art.cs.drexel.edu
  adapter: postgresql
  encoding: unicode
  database: kevin_test_test
  username: kevin_test
  password: qtdtestme
